---
title: Building a Half Adder
hero_image: images/main.png
description: Eric Coates explains the basic electronic circuit used in computer arithmetic
theme: blue
duration: 3
listed: false
ingredient: false
copyedit: false
curriculum:
interests:
technologies:
site_areas: HackSpace
steps:
- title: Introduction
  completion: engaged
- title: Exclusive OR
- title: AND Gate
- title: OR Gate
- title: NAND Gate
  completion: internal
- title: Bringing it together
